name: sqflite_support
description: sqflite support tools
version: 0.1.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  process_run:
  path:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
