name: sqflite_local_test
description: sqflite local testing
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com
# author: alex <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  sqflite:
  sqflite_test:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_test
    version: '>=0.2.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

dependency_overrides:
  sqflite_server:
    path: ../../sqflite_server
  sqflite_test:
    path: ../../sqflite_test
# Here we use a local dependency assuming we sqlite and sqflite_more at the same level
  sqflite:
    path: ../../../sqflite/sqflite
